package apigen

import (
	"fmt"
	"strconv"
	"strings"
)

func tsType(s *Schema) string {
	if s.Ref != "" {
		return schemaName(s)
	}
	if len(s.Enum) > 0 {
		parts := make([]string, len(s.Enum))
		for i, v := range s.Enum {
			parts[i] = strconv.Quote(v)
		}
		return strings.Join(parts, " | ")
	}
	if len(s.AnyOf) > 0 {
		parts := make([]string, len(s.AnyOf))
		for i, v := range s.AnyOf {
			parts[i] = tsType(v)
		}
		return "(" + strings.Join(parts, " | ") + ")"
	}
	switch s.Type {
	case "string", "boolean", "null":
		return s.Type
	case "integer", "number":
		return "number"
	case "array":
		return "Array<" + tsType(s.Items) + ">"
	case "object":
		if s.AdditionalProperties != nil {
			return "{ [key: string]: " + tsType(s.AdditionalProperties) + " }"
		}
		parts := []string{}
		for _, name := range names(s.Properties) {
			optional := ""
			if !required(s, name) {
				optional = "?"
			}
			parts = append(parts, strconv.Quote(name)+optional+": "+tsType(s.Properties[name]))
		}
		return "{ " + strings.Join(parts, "; ") + " }"
	default:
		panic("missing schema type")
	}
}
func guard(s *Schema, value string) string {
	if s.Ref != "" {
		return "is" + schemaName(s) + "(" + value + ")"
	}
	if len(s.Enum) > 0 {
		parts := []string{}
		for _, v := range s.Enum {
			parts = append(parts, value+" === "+strconv.Quote(v))
		}
		return "(" + strings.Join(parts, " || ") + ")"
	}
	if len(s.AnyOf) > 0 {
		parts := []string{}
		for _, v := range s.AnyOf {
			parts = append(parts, guard(v, value))
		}
		return "(" + strings.Join(parts, " || ") + ")"
	}
	switch s.Type {
	case "null":
		return value + " === null"
	case "string", "boolean":
		return "typeof " + value + " === " + strconv.Quote(s.Type)
	case "integer":
		return "typeof " + value + " === 'number' && Number.isInteger(" + value + ")"
	case "number":
		return "typeof " + value + " === 'number' && Number.isFinite(" + value + ")"
	case "array":
		return "Array.isArray(" + value + ") && " + value + ".every((item: unknown) => " + guard(s.Items, "item") + ")"
	case "object":
		parts := []string{"isRecord(" + value + ")"}
		if s.AdditionalProperties != nil {
			parts = append(parts, "Object.values("+value+").every((item: unknown) => "+guard(s.AdditionalProperties, "item")+")")
		}
		for _, name := range names(s.Properties) {
			field := value + "[" + strconv.Quote(name) + "]"
			check := guard(s.Properties[name], field)
			if !required(s, name) {
				check = field + " === undefined || (" + check + ")"
			}
			parts = append(parts, "("+check+")")
		}
		return strings.Join(parts, " && ")
	default:
		panic("missing guard type")
	}
}

// TypeScript generates wire types, runtime guards, and response parsers.
func (g *Types) TypeScript() []byte {
	var out strings.Builder
	out.WriteString("// Generated by Svart internal/apigen. Run make docs; do not edit.\n\n")
	out.WriteString("function isRecord(value: unknown): value is Record<string, unknown> {\n  return typeof value === 'object' && value !== null && !Array.isArray(value);\n}\n\n")
	for _, name := range names(g.Schemas) {
		s := g.Schemas[name]
		fmt.Fprintf(&out, "export type %s = %s;\nexport function is%s(value: unknown): value is %s {\n  return %s;\n}\nexport function parse%s(value: unknown): %s {\n  if (!is%s(value)) throw new Error('Invalid API response: %s');\n  return value;\n}\n\n", name, tsType(s), name, name, guard(s, "value"), name, name, name, name)
	}
	return []byte(out.String())
}

// Clients generates typed request functions for every registered operation.
func (g *Types) Clients(ops []Operation) []byte {
	var out strings.Builder
	out.WriteString("// Generated by Svart internal/apigen. Run make docs; do not edit.\nimport { request } from './client';\nimport * as schema from './generated';\n\n")
	for _, op := range ops {
		id := ID(op)
		name := strings.ToLower(id[:1]) + id[1:]
		args := []string{}
		path := op.Path
		for _, part := range strings.Split(op.Path, "/") {
			if strings.HasPrefix(part, "{") {
				key := strings.Trim(part, "{}")
				args = append(args, key+": string | number")
				path = strings.ReplaceAll(path, part, "${encodeURIComponent(String("+key+"))}")
			}
		}
		if op.Request != nil {
			args = append(args, "body: schema."+id+"Body")
		}
		args = append(args, "query?: Record<string, string>")
		fmt.Fprintf(&out, "export function %s(%s): Promise<schema.%sData> {\n  const path = `%s`;\n  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;\n  return request(requestURL, schema.parse%sData, { method: '%s'", name, strings.Join(args, ", "), id, path, id, op.Method)
		if op.Request != nil {
			out.WriteString(", body: JSON.stringify(body)")
		}
		out.WriteString(" });\n}\n\n")
	}
	return []byte(out.String())
}
