package main

import (
	"fmt"
	"path/filepath"
)

// Catalog names are basenames generated by the archiver. Reject corrupt names
// before either ownership state or files change, including resumed retention.
func summaryArchiveFilePath(directory, name string) (string, error) {
	if name == "." || !filepath.IsLocal(name) || filepath.Base(name) != name {
		return "", fmt.Errorf("invalid summary archive name %q; retain sources and repair manifest", name)
	}
	return filepath.Join(directory, name), nil
}
