// Generated by Svart internal/apigen. Run make docs; do not edit.
import { request } from './client';
import * as schema from './generated';

export function getHealth(query?: Record<string, string>): Promise<schema.GetHealthData> {
  const path = `/health`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetHealthData, { method: 'GET' });
}

export function getApiSetup(query?: Record<string, string>): Promise<schema.GetApiSetupData> {
  const path = `/api/setup`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiSetupData, { method: 'GET' });
}

export function postApiSetup(
  body: schema.PostApiSetupBody,
  query?: Record<string, string>,
): Promise<schema.PostApiSetupData> {
  const path = `/api/setup`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiSetupData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiAuthLogin(
  body: schema.PostApiAuthLoginBody,
  query?: Record<string, string>,
): Promise<schema.PostApiAuthLoginData> {
  const path = `/api/auth/login`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAuthLoginData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiAuthCheck(
  query?: Record<string, string>,
): Promise<schema.GetApiAuthCheckData> {
  const path = `/api/auth/check`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiAuthCheckData, { method: 'GET' });
}

export function postApiAuthLogout(
  query?: Record<string, string>,
): Promise<schema.PostApiAuthLogoutData> {
  const path = `/api/auth/logout`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAuthLogoutData, { method: 'POST' });
}

export function postApiAuthSessionsRevoke(
  query?: Record<string, string>,
): Promise<schema.PostApiAuthSessionsRevokeData> {
  const path = `/api/auth/sessions/revoke`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAuthSessionsRevokeData, { method: 'POST' });
}

export function getApiStats(query?: Record<string, string>): Promise<schema.GetApiStatsData> {
  const path = `/api/stats`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsData, { method: 'GET' });
}

export function getApiStatsDashboard(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsDashboardData> {
  const path = `/api/stats/dashboard`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsDashboardData, { method: 'GET' });
}

export function getApiStatsTimeseries(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsTimeseriesData> {
  const path = `/api/stats/timeseries`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsTimeseriesData, { method: 'GET' });
}

export function getApiStatsTopClients(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsTopClientsData> {
  const path = `/api/stats/top-clients`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsTopClientsData, { method: 'GET' });
}

export function getApiStatsBlockSources(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsBlockSourcesData> {
  const path = `/api/stats/block-sources`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsBlockSourcesData, { method: 'GET' });
}

export function getApiStatsUpstreamUsage(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsUpstreamUsageData> {
  const path = `/api/stats/upstream-usage`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsUpstreamUsageData, { method: 'GET' });
}

export function getApiStatsTopDomains(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsTopDomainsData> {
  const path = `/api/stats/top-domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsTopDomainsData, { method: 'GET' });
}

export function getApiStatsLatency(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsLatencyData> {
  const path = `/api/stats/latency`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsLatencyData, { method: 'GET' });
}

export function getApiStatsServfails(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsServfailsData> {
  const path = `/api/stats/servfails`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsServfailsData, { method: 'GET' });
}

export function getApiStatsSystem(
  query?: Record<string, string>,
): Promise<schema.GetApiStatsSystemData> {
  const path = `/api/stats/system`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiStatsSystemData, { method: 'GET' });
}

export function getApiUpstreams(
  query?: Record<string, string>,
): Promise<schema.GetApiUpstreamsData> {
  const path = `/api/upstreams`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiUpstreamsData, { method: 'GET' });
}

export function postApiUpstreams(
  body: schema.PostApiUpstreamsBody,
  query?: Record<string, string>,
): Promise<schema.PostApiUpstreamsData> {
  const path = `/api/upstreams`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiUpstreamsData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function putApiUpstreamsId(
  id: string | number,
  body: schema.PutApiUpstreamsIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiUpstreamsIdData> {
  const path = `/api/upstreams/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiUpstreamsIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiUpstreamsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiUpstreamsIdData> {
  const path = `/api/upstreams/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiUpstreamsIdData, { method: 'DELETE' });
}

export function postApiUpstreamsIdToggle(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiUpstreamsIdToggleData> {
  const path = `/api/upstreams/${encodeURIComponent(String(id))}/toggle`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiUpstreamsIdToggleData, { method: 'POST' });
}

export function getApiBlocklists(
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsData> {
  const path = `/api/blocklists`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsData, { method: 'GET' });
}

export function postApiBlocklists(
  body: schema.PostApiBlocklistsBody,
  query?: Record<string, string>,
): Promise<schema.PostApiBlocklistsData> {
  const path = `/api/blocklists`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiBlocklistsData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiBlocklistsIdDomains(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsIdDomainsData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}/domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsIdDomainsData, { method: 'GET' });
}

export function getApiBlocklistsIdCompatibility(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsIdCompatibilityData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}/compatibility`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsIdCompatibilityData, { method: 'GET' });
}

export function putApiBlocklistsId(
  id: string | number,
  body: schema.PutApiBlocklistsIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiBlocklistsIdData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiBlocklistsIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiBlocklistsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiBlocklistsIdData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiBlocklistsIdData, { method: 'DELETE' });
}

export function postApiBlocklistsIdToggle(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiBlocklistsIdToggleData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}/toggle`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiBlocklistsIdToggleData, { method: 'POST' });
}

export function postApiBlocklistsIdRefresh(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiBlocklistsIdRefreshData> {
  const path = `/api/blocklists/${encodeURIComponent(String(id))}/refresh`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiBlocklistsIdRefreshData, { method: 'POST' });
}

export function getApiAllowlists(
  query?: Record<string, string>,
): Promise<schema.GetApiAllowlistsData> {
  const path = `/api/allowlists`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiAllowlistsData, { method: 'GET' });
}

export function postApiAllowlists(
  body: schema.PostApiAllowlistsBody,
  query?: Record<string, string>,
): Promise<schema.PostApiAllowlistsData> {
  const path = `/api/allowlists`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAllowlistsData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiAllowlistsIdDomains(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiAllowlistsIdDomainsData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}/domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiAllowlistsIdDomainsData, { method: 'GET' });
}

export function getApiAllowlistsIdCompatibility(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiAllowlistsIdCompatibilityData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}/compatibility`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiAllowlistsIdCompatibilityData, { method: 'GET' });
}

export function putApiAllowlistsId(
  id: string | number,
  body: schema.PutApiAllowlistsIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiAllowlistsIdData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiAllowlistsIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiAllowlistsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiAllowlistsIdData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiAllowlistsIdData, { method: 'DELETE' });
}

export function postApiAllowlistsIdToggle(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiAllowlistsIdToggleData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}/toggle`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAllowlistsIdToggleData, { method: 'POST' });
}

export function postApiAllowlistsIdRefresh(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiAllowlistsIdRefreshData> {
  const path = `/api/allowlists/${encodeURIComponent(String(id))}/refresh`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAllowlistsIdRefreshData, { method: 'POST' });
}

export function getApiBlocklistsHistory(
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsHistoryData> {
  const path = `/api/blocklists/history`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsHistoryData, { method: 'GET' });
}

export function getApiBlocklistsHistoryHistoryIdDomains(
  historyId: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsHistoryHistoryIdDomainsData> {
  const path = `/api/blocklists/history/${encodeURIComponent(String(historyId))}/domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsHistoryHistoryIdDomainsData, {
    method: 'GET',
  });
}

export function getApiBlocklistsUniqueDomains(
  query?: Record<string, string>,
): Promise<schema.GetApiBlocklistsUniqueDomainsData> {
  const path = `/api/blocklists/unique-domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBlocklistsUniqueDomainsData, { method: 'GET' });
}

export function getApiSettings(query?: Record<string, string>): Promise<schema.GetApiSettingsData> {
  const path = `/api/settings`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiSettingsData, { method: 'GET' });
}

export function putApiSettingsKey(
  key: string | number,
  body: schema.PutApiSettingsKeyBody,
  query?: Record<string, string>,
): Promise<schema.PutApiSettingsKeyData> {
  const path = `/api/settings/${encodeURIComponent(String(key))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiSettingsKeyData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function getApiBootstrap(
  query?: Record<string, string>,
): Promise<schema.GetApiBootstrapData> {
  const path = `/api/bootstrap`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiBootstrapData, { method: 'GET' });
}

export function postApiBootstrap(
  body: schema.PostApiBootstrapBody,
  query?: Record<string, string>,
): Promise<schema.PostApiBootstrapData> {
  const path = `/api/bootstrap`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiBootstrapData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function putApiBootstrap(
  body: schema.PutApiBootstrapBody,
  query?: Record<string, string>,
): Promise<schema.PutApiBootstrapData> {
  const path = `/api/bootstrap`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiBootstrapData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function postApiCacheClear(
  query?: Record<string, string>,
): Promise<schema.PostApiCacheClearData> {
  const path = `/api/cache/clear`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiCacheClearData, { method: 'POST' });
}

export function getApiClients(query?: Record<string, string>): Promise<schema.GetApiClientsData> {
  const path = `/api/clients`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiClientsData, { method: 'GET' });
}

export function getApiClientsIp(
  ip: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiClientsIpData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiClientsIpData, { method: 'GET' });
}

export function putApiClientsIpAlias(
  ip: string | number,
  body: schema.PutApiClientsIpAliasBody,
  query?: Record<string, string>,
): Promise<schema.PutApiClientsIpAliasData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/alias`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiClientsIpAliasData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function getApiGroups(query?: Record<string, string>): Promise<schema.GetApiGroupsData> {
  const path = `/api/groups`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiGroupsData, { method: 'GET' });
}

export function postApiGroups(
  body: schema.PostApiGroupsBody,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsData> {
  const path = `/api/groups`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiGroupsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiGroupsIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiGroupsIdData, { method: 'GET' });
}

export function putApiGroupsId(
  id: string | number,
  body: schema.PutApiGroupsIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiGroupsIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiGroupsIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiGroupsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdData, { method: 'DELETE' });
}

export function postApiGroupsIdBlocklistsBatch(
  id: string | number,
  body: schema.PostApiGroupsIdBlocklistsBatchBody,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdBlocklistsBatchData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/blocklists/batch`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdBlocklistsBatchData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiGroupsIdMembersBatch(
  id: string | number,
  body: schema.PostApiGroupsIdMembersBatchBody,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdMembersBatchData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/members/batch`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdMembersBatchData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiRanges(query?: Record<string, string>): Promise<schema.GetApiRangesData> {
  const path = `/api/ranges`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiRangesData, { method: 'GET' });
}

export function postApiRanges(
  body: schema.PostApiRangesBody,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesData> {
  const path = `/api/ranges`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiRangesId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiRangesIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiRangesIdData, { method: 'GET' });
}

export function putApiRangesId(
  id: string | number,
  body: schema.PutApiRangesIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiRangesIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiRangesIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiRangesId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdData, { method: 'DELETE' });
}

export function getApiPolicies(query?: Record<string, string>): Promise<schema.GetApiPoliciesData> {
  const path = `/api/policies`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiPoliciesData, { method: 'GET' });
}

export function postApiPolicies(
  body: schema.PostApiPoliciesBody,
  query?: Record<string, string>,
): Promise<schema.PostApiPoliciesData> {
  const path = `/api/policies`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPoliciesData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiPoliciesId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiPoliciesIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiPoliciesIdData, { method: 'GET' });
}

export function putApiPoliciesId(
  id: string | number,
  body: schema.PutApiPoliciesIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiPoliciesIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiPoliciesIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiPoliciesId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPoliciesIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPoliciesIdData, { method: 'DELETE' });
}

export function postApiClientsIpBlocklistsListId(
  ip: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpBlocklistsListIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpBlocklistsListIdData, { method: 'POST' });
}

export function postApiGroupsIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdBlocklistsListIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdBlocklistsListIdData, { method: 'POST' });
}

export function postApiRangesIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesIdBlocklistsListIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesIdBlocklistsListIdData, { method: 'POST' });
}

export function postApiClientsIpAllowlistsListId(
  ip: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpAllowlistsListIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpAllowlistsListIdData, { method: 'POST' });
}

export function postApiGroupsIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdAllowlistsListIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdAllowlistsListIdData, { method: 'POST' });
}

export function postApiRangesIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesIdAllowlistsListIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesIdAllowlistsListIdData, { method: 'POST' });
}

export function postApiClientsIpGroupsGroupId(
  ip: string | number,
  groupId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpGroupsGroupIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/groups/${encodeURIComponent(String(groupId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpGroupsGroupIdData, { method: 'POST' });
}

export function postApiGroupsIdMembersIp(
  id: string | number,
  ip: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdMembersIpData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/members/${encodeURIComponent(String(ip))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdMembersIpData, { method: 'POST' });
}

export function deleteApiClientsIpBlocklistsListId(
  ip: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpBlocklistsListIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpBlocklistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiGroupsIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdBlocklistsListIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdBlocklistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiRangesIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdBlocklistsListIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdBlocklistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiClientsIpAllowlistsListId(
  ip: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpAllowlistsListIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpAllowlistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiGroupsIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdAllowlistsListIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdAllowlistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiRangesIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdAllowlistsListIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdAllowlistsListIdData, {
    method: 'DELETE',
  });
}

export function deleteApiClientsIpGroupsGroupId(
  ip: string | number,
  groupId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpGroupsGroupIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/groups/${encodeURIComponent(String(groupId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpGroupsGroupIdData, { method: 'DELETE' });
}

export function deleteApiGroupsIdMembersIp(
  id: string | number,
  ip: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdMembersIpData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/members/${encodeURIComponent(String(ip))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdMembersIpData, { method: 'DELETE' });
}

export function postApiClientsIpPolicyPolicyId(
  ip: string | number,
  policyId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpPolicyPolicyIdData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/policy/${encodeURIComponent(String(policyId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpPolicyPolicyIdData, { method: 'POST' });
}

export function deleteApiClientsIpPolicy(
  ip: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpPolicyData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/policy`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpPolicyData, { method: 'DELETE' });
}

export function postApiGroupsIdPolicyPolicyId(
  id: string | number,
  policyId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdPolicyPolicyIdData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/policy/${encodeURIComponent(String(policyId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdPolicyPolicyIdData, { method: 'POST' });
}

export function deleteApiGroupsIdPolicy(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdPolicyData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/policy`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdPolicyData, { method: 'DELETE' });
}

export function postApiRangesIdPolicyPolicyId(
  id: string | number,
  policyId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesIdPolicyPolicyIdData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/policy/${encodeURIComponent(String(policyId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesIdPolicyPolicyIdData, { method: 'POST' });
}

export function deleteApiRangesIdPolicy(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdPolicyData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/policy`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdPolicyData, { method: 'DELETE' });
}

export function postApiPoliciesIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiPoliciesIdBlocklistsListIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPoliciesIdBlocklistsListIdData, { method: 'POST' });
}

export function deleteApiPoliciesIdBlocklistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPoliciesIdBlocklistsListIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/blocklists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPoliciesIdBlocklistsListIdData, {
    method: 'DELETE',
  });
}

export function postApiPoliciesIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.PostApiPoliciesIdAllowlistsListIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPoliciesIdAllowlistsListIdData, { method: 'POST' });
}

export function deleteApiPoliciesIdAllowlistsListId(
  id: string | number,
  listId: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPoliciesIdAllowlistsListIdData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/allowlists/${encodeURIComponent(String(listId))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPoliciesIdAllowlistsListIdData, {
    method: 'DELETE',
  });
}

export function postApiClientsIpBlockDomain(
  ip: string | number,
  body: schema.PostApiClientsIpBlockDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpBlockDomainData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/block-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpBlockDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiClientsIpBlockDomainDomain(
  ip: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpBlockDomainDomainData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/block-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpBlockDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiClientsIpAllowDomain(
  ip: string | number,
  body: schema.PostApiClientsIpAllowDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiClientsIpAllowDomainData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/allow-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiClientsIpAllowDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiClientsIpAllowDomainDomain(
  ip: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiClientsIpAllowDomainDomainData> {
  const path = `/api/clients/${encodeURIComponent(String(ip))}/allow-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiClientsIpAllowDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiGroupsIdBlockDomain(
  id: string | number,
  body: schema.PostApiGroupsIdBlockDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdBlockDomainData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/block-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdBlockDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiGroupsIdBlockDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdBlockDomainDomainData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/block-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdBlockDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiGroupsIdAllowDomain(
  id: string | number,
  body: schema.PostApiGroupsIdAllowDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiGroupsIdAllowDomainData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/allow-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiGroupsIdAllowDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiGroupsIdAllowDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiGroupsIdAllowDomainDomainData> {
  const path = `/api/groups/${encodeURIComponent(String(id))}/allow-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiGroupsIdAllowDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiPoliciesIdBlockDomain(
  id: string | number,
  body: schema.PostApiPoliciesIdBlockDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiPoliciesIdBlockDomainData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/block-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPoliciesIdBlockDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiPoliciesIdBlockDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPoliciesIdBlockDomainDomainData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/block-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPoliciesIdBlockDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiPoliciesIdAllowDomain(
  id: string | number,
  body: schema.PostApiPoliciesIdAllowDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiPoliciesIdAllowDomainData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/allow-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPoliciesIdAllowDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiPoliciesIdAllowDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPoliciesIdAllowDomainDomainData> {
  const path = `/api/policies/${encodeURIComponent(String(id))}/allow-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPoliciesIdAllowDomainDomainData, {
    method: 'DELETE',
  });
}

export function getApiRewrites(query?: Record<string, string>): Promise<schema.GetApiRewritesData> {
  const path = `/api/rewrites`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiRewritesData, { method: 'GET' });
}

export function postApiRewrites(
  body: schema.PostApiRewritesBody,
  query?: Record<string, string>,
): Promise<schema.PostApiRewritesData> {
  const path = `/api/rewrites`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRewritesData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function putApiRewritesId(
  id: string | number,
  body: schema.PutApiRewritesIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiRewritesIdData> {
  const path = `/api/rewrites/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiRewritesIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiRewritesId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRewritesIdData> {
  const path = `/api/rewrites/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRewritesIdData, { method: 'DELETE' });
}

export function postApiRewritesBatch(
  body: schema.PostApiRewritesBatchBody,
  query?: Record<string, string>,
): Promise<schema.PostApiRewritesBatchData> {
  const path = `/api/rewrites/batch`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRewritesBatchData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiRewritesStats(
  query?: Record<string, string>,
): Promise<schema.GetApiRewritesStatsData> {
  const path = `/api/rewrites/stats`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiRewritesStatsData, { method: 'GET' });
}

export function getApiQueryLogs(
  query?: Record<string, string>,
): Promise<schema.GetApiQueryLogsData> {
  const path = `/api/query-logs`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiQueryLogsData, { method: 'GET' });
}

export function getApiQueryLogsId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.GetApiQueryLogsIdData> {
  const path = `/api/query-logs/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiQueryLogsIdData, { method: 'GET' });
}

export function getApiPolicyEvaluate(
  query?: Record<string, string>,
): Promise<schema.GetApiPolicyEvaluateData> {
  const path = `/api/policy/evaluate`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiPolicyEvaluateData, { method: 'GET' });
}

export function postApiAnalysisCompare(
  body: schema.PostApiAnalysisCompareBody,
  query?: Record<string, string>,
): Promise<schema.PostApiAnalysisCompareData> {
  const path = `/api/analysis/compare`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAnalysisCompareData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiAnalysisMatrix(
  body: schema.PostApiAnalysisMatrixBody,
  query?: Record<string, string>,
): Promise<schema.PostApiAnalysisMatrixData> {
  const path = `/api/analysis/matrix`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAnalysisMatrixData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiAnalysisSimulate(
  body: schema.PostApiAnalysisSimulateBody,
  query?: Record<string, string>,
): Promise<schema.PostApiAnalysisSimulateData> {
  const path = `/api/analysis/simulate`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiAnalysisSimulateData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiAnalysisDomains(
  query?: Record<string, string>,
): Promise<schema.GetApiAnalysisDomainsData> {
  const path = `/api/analysis/domains`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiAnalysisDomainsData, { method: 'GET' });
}

export function getApiTokens(query?: Record<string, string>): Promise<schema.GetApiTokensData> {
  const path = `/api/tokens`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiTokensData, { method: 'GET' });
}

export function postApiTokens(
  body: schema.PostApiTokensBody,
  query?: Record<string, string>,
): Promise<schema.PostApiTokensData> {
  const path = `/api/tokens`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiTokensData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiTokensId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiTokensIdData> {
  const path = `/api/tokens/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiTokensIdData, { method: 'DELETE' });
}

export function getApiUsers(query?: Record<string, string>): Promise<schema.GetApiUsersData> {
  const path = `/api/users`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiUsersData, { method: 'GET' });
}

export function postApiUsers(
  body: schema.PostApiUsersBody,
  query?: Record<string, string>,
): Promise<schema.PostApiUsersData> {
  const path = `/api/users`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiUsersData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function putApiUsersId(
  id: string | number,
  body: schema.PutApiUsersIdBody,
  query?: Record<string, string>,
): Promise<schema.PutApiUsersIdData> {
  const path = `/api/users/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePutApiUsersIdData, {
    method: 'PUT',
    body: JSON.stringify(body),
  });
}

export function deleteApiUsersId(
  id: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiUsersIdData> {
  const path = `/api/users/${encodeURIComponent(String(id))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiUsersIdData, { method: 'DELETE' });
}

export function getApiConfigExport(
  query?: Record<string, string>,
): Promise<schema.GetApiConfigExportData> {
  const path = `/api/config/export`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiConfigExportData, { method: 'GET' });
}

export function postApiConfigImport(
  body: schema.PostApiConfigImportBody,
  query?: Record<string, string>,
): Promise<schema.PostApiConfigImportData> {
  const path = `/api/config/import`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiConfigImportData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiArchive(query?: Record<string, string>): Promise<schema.PostApiArchiveData> {
  const path = `/api/archive`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiArchiveData, { method: 'POST' });
}

export function getApiArchiveStatus(
  query?: Record<string, string>,
): Promise<schema.GetApiArchiveStatusData> {
  const path = `/api/archive/status`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiArchiveStatusData, { method: 'GET' });
}

export function getApiSync(query?: Record<string, string>): Promise<schema.GetApiSyncData> {
  const path = `/api/sync`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiSyncData, { method: 'GET' });
}

export function getApiPeers(query?: Record<string, string>): Promise<schema.GetApiPeersData> {
  const path = `/api/peers`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiPeersData, { method: 'GET' });
}

export function postApiPeers(
  body: schema.PostApiPeersBody,
  query?: Record<string, string>,
): Promise<schema.PostApiPeersData> {
  const path = `/api/peers`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPeersData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiPeersUrl(
  url: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiPeersUrlData> {
  const path = `/api/peers/${encodeURIComponent(String(url))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiPeersUrlData, { method: 'DELETE' });
}

export function postApiPeersPair(
  query?: Record<string, string>,
): Promise<schema.PostApiPeersPairData> {
  const path = `/api/peers/pair`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPeersPairData, { method: 'POST' });
}

export function postApiPeersConfirm(
  body: schema.PostApiPeersConfirmBody,
  query?: Record<string, string>,
): Promise<schema.PostApiPeersConfirmData> {
  const path = `/api/peers/confirm`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiPeersConfirmData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiSyncPairComplete(
  body: schema.PostApiSyncPairCompleteBody,
  query?: Record<string, string>,
): Promise<schema.PostApiSyncPairCompleteData> {
  const path = `/api/sync/pair/complete`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiSyncPairCompleteData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function postApiInvestigate(
  body: schema.PostApiInvestigateBody,
  query?: Record<string, string>,
): Promise<schema.PostApiInvestigateData> {
  const path = `/api/investigate`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiInvestigateData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function getApiInvestigateSchema(
  query?: Record<string, string>,
): Promise<schema.GetApiInvestigateSchemaData> {
  const path = `/api/investigate/schema`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseGetApiInvestigateSchemaData, { method: 'GET' });
}

export function postApiRangesIdBlockDomain(
  id: string | number,
  body: schema.PostApiRangesIdBlockDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesIdBlockDomainData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/block-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesIdBlockDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiRangesIdBlockDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdBlockDomainDomainData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/block-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdBlockDomainDomainData, {
    method: 'DELETE',
  });
}

export function postApiRangesIdAllowDomain(
  id: string | number,
  body: schema.PostApiRangesIdAllowDomainBody,
  query?: Record<string, string>,
): Promise<schema.PostApiRangesIdAllowDomainData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/allow-domain`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parsePostApiRangesIdAllowDomainData, {
    method: 'POST',
    body: JSON.stringify(body),
  });
}

export function deleteApiRangesIdAllowDomainDomain(
  id: string | number,
  domain: string | number,
  query?: Record<string, string>,
): Promise<schema.DeleteApiRangesIdAllowDomainDomainData> {
  const path = `/api/ranges/${encodeURIComponent(String(id))}/allow-domain/${encodeURIComponent(String(domain))}`;
  const requestURL = query ? `${path}?${new URLSearchParams(query)}` : path;
  return request(requestURL, schema.parseDeleteApiRangesIdAllowDomainDomainData, {
    method: 'DELETE',
  });
}
